/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.utpl.javasilabopersist.rest;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author root
 */
@javax.ws.rs.ApplicationPath("webresources")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        // following code can be used to customize Jersey 1.x JSON provider:
        try {
            Class jacksonProvider = Class.forName("org.codehaus.jackson.jaxrs.JacksonJsonProvider");
            resources.add(jacksonProvider);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getClass().getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(com.utpl.javasilabopersist.rest.CarreraFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.CicloFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.ContenidoFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.CorrequisitosFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.EjeFormacionFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.EscuelaFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.FacultadFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.LogroFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.LogrosFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.MallaFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.MateriaFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.MateriaMallaFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.MateriatFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.ModalidadFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.PeriodoFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.ProfesorFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.ProfesortFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.RecursosFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.ReferenciaFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.RequisitosFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.SilaboFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.SilaboReferenciaFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.TipoMateriaFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.TipoReferenciaFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.TipoTFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.TipoUFacadeREST.class);
        resources.add(com.utpl.javasilabopersist.rest.VersionMallaFacadeREST.class);
    }
    
}
